config/routes.rb
Rails.application.routes.draw do
  resources :news, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :booktime, only: [:index, :new]
  root 'news#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'booktime', to: 'booktime#new'
end

app/models/new.rb
class New < ActiveRecord::Base
    
    validates :user_id, presence: true
    validates :title, presence: true, length: { minimum: 3, maximum: 120 }
    belongs_to :user
    has_one_attached :picture
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

    before_action :require_user, except: [:index]

    before_action :set_item, only: [:update, :edit, :destroy]

    def index
        puts '============================TRACK NAME================================='  
        puts params[:search]
        if params[:search]
            @results = New.where("title LIKE ?", "%#{params[:search]}%").or(New.where("description LIKE ?", "%#{params[:search]}%"))
        else
            @results = New.order("created_at DESC")
        end
    end

    def set_item
        @itemid = New.find(params[:id])
    end

 
    def create
        @newsitem = New.new(item_parameters)
        @newsitem.user = current_user
        if @newsitem.save
            puts "Yes it was saved"
            flash[:success] = "Julkaistettu onnistuneesti"
            redirect_to root_path
        else
            puts 'Not saved'
            render 'new'
            flash[:warning] = "Virhe. Viesti ei ole tallennetu"
            redirect_to root_path
        end
    end


    def update
        puts @itemid.title
        puts @itemid.description
        puts 'New data:'
        puts params[:new][:title]
        puts params[:new][:description]
        puts 'Json string'
        puts params
        puts params[:new]

        #if there is no picture added, leave the picture that already exist
        if @itemid.picture.attached? && params[:new][:picture].blank?

                # Update only title and description
                @itemid.update(title: params[:new][:title], description: params[:new][:description])

        else
            @itemid.update(title: params[:new][:title], description: params[:new][:description], picture: params[:new][:picture])

        end

        if params[:new][:imagename]
            @itemid.update(picture_path: params[:new][:imagename])
            puts 'item local picture was updated'
        end

        if @itemid.save
            flash[:success] = "Päivitetty onnistuneesti"
        else
            flash[:warning] = "Virhe. Viesti ei ole päivitetty!"
        end
        redirect_to root_path
    end


    def edit
        if @itemid.user != current_user
            flash[:danger] = "Estetty. Ei ole oikeutta."
            redirect_to root_path
        end
    end

    def show
    end

    def destroy
        if @itemid.user == current_user
            if @itemid.destroy
                flash[:success] = "Viesti oli poistettu"
                redirect_to root_path
            else
                flash[:danger] = "Virhe. Viesti ei ole poistettu!"
                redirect_to root_path
            end
        else
            flash[:danger] = "Estetty. Poistaminen ei onnistunut. Ei ole käyttöoikeuksia."
        end
    end

    private
        def new_parameters
            params.require(:new).permit(:title, :description, :picture)
        end

        def item_parameters
            params.permit(:title, :description, :picture)
        end

        def search_params
            params.permit(:search)
        end
        
    
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with  model: @newsitemas  do |f| %>
    <div class="form-group">
        <%= f.text_field :title, :class => 'form-control mb-10', value: @itemid.title %>
    </div>
    <div class="form-group">
        <%= f.text_area :description, :class => 'form-control mb-10', value: @itemid.description %>
    </div>
<%= f.submit "Julkaista", :class => 'primary-btn submit_btn' %>


<% end %>

app/views/news/_form_add_news_item.html.erb
                <div class="comment-form">
                    <h3>Mitä uutta?</h3>
                        <%= form_with  model: @newsitem do |f| %>
                            <div class="form-group">
                                <%= f.text_field :title, :class => 'form-control mb-10' %>
                            </div>
                            <div class="form-group">
                                <%= f.label "Kuva:" %>
                                <%= f.file_field :picture %><br>
                            </div>
                            <div class="form-group">
                                <%= f.text_area :description, :class => 'form-control mb-10' %>
                            </div>
                        <%= f.submit "Julkaista", :class => 'primary-btn submit_btn' %>
                        <% end %>
                </div>

app/views/news/edit.html.erb
        <% flash.each do |name, msg| %>
            <ul>
                 <li><%= msg %></li>
            </ul>
        <% end %>
		<%- # ================Home Banner Area =================-%>
        <section class="banner_area">
            <div class="box_1620">
				<div class="text-center">
					<div class="container">
						<div class="banner_content text-center">
							<h2> Viestieditori</h2>
						</div>
						<div class="main_title">
							<p>Tämän lomakeen avulla voit muokkaa jo oleva viesti</p>
                                                        <p><%= link_to "<- Palaa ajankohtaista-sivulle", root_path %></p>
						</div>
					</div>
				</div>
            </div>
        </section>
        <%- # ================End Home Banner Area =================-%>

        <%- # ================Blog Area =================-%>
        <section class="blog_area single-post-area p-120">
            <div class="container">
                <div class="comment-form">
                    <h3>Muokkaa viesti</h3>
                        <div class="feature-img">
                            <% if @itemid.picture.attached? %>
                                <img class="img-fluid" src="<%=(url_for(@itemid.picture)) %>">
                            <% end %>
                        </div>
                        <%= form_with model: @itemid, url: { action: "update" }, method: "put" do |f| %>
                                <div class="form-group">
                                    <%= f.label "Kuva" %>
                                    <%= f.file_field :picture %>
                                    <%= link_to "Poistaa kuva", @itemid.picture.purge, data: {confirm: "Oletko varma että haluat poistaa kuva?"} %><br>
                                    <% if @current_user.id == 3 %>
                                        <%= f.text_field :imagename, class: 'form-control mb-10' %>
                                    <% end %>
                                </div>
                                <div class="form-group">
                                    <%= f.text_field :title, :class => 'form-control mb-10' %>
                                </div>
                                <div class="form-group">
                                    <%= f.text_area :description, :class => 'form-control mb-10' %>
                                </div>
                                
                            <%= f.submit "Julkaista", :class => 'primary-btn submit_btn' %>

                        <% end %>



                </div>
            </div>
        </section>
        <%- # ================Blog Area =================-%>

        <%- # ================Footer Area =================-%>
        <footer class="footer_area p_120">
        	<div class="container">
        		<div class="row footer_inner">
        			<div class="col-lg-5 col-sm-6">
        				<aside class="f_widget ab_widget">
        					<div class="f_title">
        						<h3>About Me</h3>
        					</div>
        					<p>
								I am an result-focused IT junior programmer with the necessary skills in Software development. 
								I work with Windows and Linux computers on an advanced level and learn quickly any new programs.
								I am interested in IT technologies and spend a lot of time developing my skills in that area.
							</p>
        					<%- #  Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -%>
                                                <p>
Copyright &copy;2020 All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>

    <%- #  Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -%> 
                                        </aside>
        			</div>
        			<div class="col-lg-5 col-sm-6">
        				<aside class="f_widget news_widget">
        					<div class="f_title">
        						<h3>Contact me</h3>
        					</div>
        					<p><a href="tel:+358449890965">+358 (0) 44 989 09 65<a/></p>
							<p><a href="mailto:vladimir.gavrilov@hotmail.com">vladimir.gavrilov@hotmail.com</a></p>
        					
        				</aside>
        			</div>
        			<div class="col-lg-2">
        				<aside class="f_widget social_widget">
        					<div class="f_title">
        						<h3>Follow Me</h3>
        					</div>
        					<p>Let us be social</p>
        					<ul class="list">
        						<li><a href="https://www.instagram.com/vld.gvrl/"><i class="fa fa-instagram"></i></a></li>
        						<li><a href="https://www.linkedin.com/in/vladimir-gavrilov-53055112a/"><i class="fa fa-linkedin"></i></a></li>
        						<li><a href="https://youtu.be/PsJgw7sRsuc"><i class="fa fa-youtube"></i></a></li>
								<li><a href="https://github.com/vldgvrl"><i class="fa fa-github"></i></a></li>
        					</ul>
        				</aside>
        			</div>
        		</div>
        	</div>
        </footer>
        <%- # ================End Footer Area =================-%>

app/views/news/index.html.erb
		<%- # ================Home Banner Area =================-%>
        <section class="banner_area">
						<div class="banner_content text-center">
							<h2>Ajankohtaista </h2>
						</div>
						<div class="main_title">
							<p>Tässä haluan kertoa minun tärkeästä uusista kokemuksista, taidoista, sekä näyttää minun osaamista <strong>"Ruby on Rails"</strong> käyttämisessä tämän sivun avulla</p> 
                                                        <% if !logged_in? %>
                                                            <%= link_to "Kirjaudu sisään testiympäristöön", login_path %>
                                                            <% else %>
                                                            <%= link_to "Kirjaudu ulos", logout_path, method: :delete %>
                                                        <% end %>
						</div>
        </section>
        <%- # ================End Home Banner Area =================-%>

        <%- # ================Blog Area =================-%>
        <section class="blog_area single-post-area p-120"> 
          <%= render 'shared/status_messages' %>
            <div class="container">
                <% if logged_in? %>
                <%= render 'news/form_add_news_item' %>
                <% end %>
                    <div class="search_row">
                            <div class="blog_right_sidebar">
                                <aside class="single_sidebar_widget search_widget">
                                        <%= form_with url: '/news', method: "get", local: true do |f| %>
                                            <div class="input-group">
                                                <%= f.text_field :search, id: params[:search], placeholder: "Haku", class: "form-control" %>
                                                <span class="input-group-btn">
                                                    <%= f.submit "", class: "btn btn-default"%>
                                                </span>
                                            </div><!-- /input-group -->
                                        <% end %>
                                </aside>
                            </div>
                    </div>
                <div class="row">
                    <div class="col-lg-8 posts-list">
                    <% if params[:search] %>
                        <div class="search_label">
                            <h2>Hakusana "<%= params[:search] %>":</h2>
                        </div>

                    <% end %>
                        <% @results.each do |newsitem| %>
                            <div class="single-post-area">
                                <div class="feature-img">
                                    <% begin %>
                                        <%= image_tag  url_for(newsitem.picture), class:"img-fluid" %>
                                    <% rescue => e%>
                                        <%= image_tag  url_for(newsitem.picture_path), class:"img-fluid" %>
                                    <% end %>
                                </div>
                                <div class="row">
                                    <div class="col-lg-3  col-md-3">
                                        <div class="blog_info text-right">
                                            <i class="fa fa-calendar"></i><%= newsitem.created_at.strftime("%d.%m.%y") %>
                                            <i class="fa fa-clock-o"></i><%= newsitem.created_at.strftime("%H:%M") %>

                                        </div>
                                    </div>
                                    <div class="col-lg-9 col-md-9 blog_details">
                                        <h2><%= newsitem.title %></h2>
                                    </div>
                                </div>
                            <div class="col-lg-12">
                                <p class="excert">
                                    <%= newsitem.description.gsub(/\n/, '<br />').html_safe %>
                                </p>
                            </div>
                    </div>
                        <div class="navigation-area">
                            <ul>
                              <% if logged_in? %>
                                <li><%= link_to 'Muokkaa', edit_news_path(newsitem) %></li>
                                <li><%= link_to 'Poista', news_path(newsitem), method: :delete, data: {confirm: "Oletko varma että haluat poistaa tämän julkaisun?"} %></li>
                              <% end %>
                            </ul>
                        </div>
                        <% end %>
                </div>
                <div class="col-lg-4">
                    <div class="navigation-area">
                        <div class="row">
                            <div class="blog_right_sidebar">
                                <aside class="single-sidebar-widget newsletter_widget">
                                    <h4 class="widget_title">Lähetä kutsu minulle</h4>
							
                                    <p class="mb-3">Varata aika keskusteluun minun kanssa, käytämällä tämän lomakke</p>
                                    <%= form_with url: '/booktime' do |f| %>
                                        <div class="row">
                                            <div class="col-lg-6">
                                                <div class="form-group">
                                                    <%= f.date_field :date, as: :date, value: f.object.try(:strftime, "%d,%m,%Y"),  :class => 'form-control mb-10', placeholder: 'Päivämäärä:' %>
                                                </div>
                                            </div>
                                            <div class="col-lg-4">
                                                <div class="form-group">
                                                    <%= f.time_field :time, as: :time, value: f.object.try(:strftime, "%HH,%MM"),  :class => 'form-control mb-10', placeholder: 'Klo:' %>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <%= f.email_field :email, :class => 'form-control mb-10', placeholder: 'Sähköposti osoite:' %>
                                        </div>
                                        <div class="form-group">
                                            <%= f.text_area :message, :class => 'form-control mb-10', placeholder: 'Viesti:' %>
                                        </div>
                                    <%= f.submit "Lähetä kutsu", :class => 'bbtns' %>
                                    <% end %>
                                    <div class="br"></div>							
                                </aside>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <%- # ================Blog Area =================-%>

        <%- # ================Footer Area =================-%>
        <footer class="footer_area p_120">
        	<div class="container">
        		<div class="row footer_inner">
        			<div class="col-lg-5 col-sm-6">
        				<aside class="f_widget ab_widget">
        					<div class="f_title">
        						<h3>About Me</h3>
        					</div>
        					<p>
								I am an result-focused IT junior programmer with the necessary skills in Software development. 
								I work with Windows and Linux computers on an advanced level and learn quickly any new programs.
								I am interested in IT technologies and spend a lot of time developing my skills in that area.
							</p>
        					<%- #  Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -%>
                                                <p>
Copyright &copy;2020 All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>

    <%- #  Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -%> 
                                        </aside>
        			</div>
        			<div class="col-lg-5 col-sm-6">
        				<aside class="f_widget news_widget">
        					<div class="f_title">
        						<h3>Contact me</h3>
        					</div>
        					<p><a href="tel:+358449890965">+358 (0) 44 989 09 65<a/></p>
							<p><a href="mailto:vladimir.gavrilov@hotmail.com">vladimir.gavrilov@hotmail.com</a></p>
        					
        				</aside>
        			</div>
        			<div class="col-lg-2">
        				<aside class="f_widget social_widget">
        					<div class="f_title">
        						<h3>Follow Me</h3>
        					</div>
        					<p>Let us be social</p>
        					<ul class="list">
        						<li><a href="https://www.instagram.com/vld.gvrl/"><i class="fa fa-instagram"></i></a></li>
        						<li><a href="https://www.linkedin.com/in/vladimir-gavrilov-53055112a/"><i class="fa fa-linkedin"></i></a></li>
        						<li><a href="https://youtu.be/PsJgw7sRsuc"><i class="fa fa-youtube"></i></a></li>
								<li><a href="https://github.com/vldgvrl"><i class="fa fa-github"></i></a></li>
        					</ul>
        				</aside>
        			</div>
        		</div>
        	</div>
        </footer>
        <%- # ================End Footer Area =================-%>